/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ad.ieseljust.ModulsToJSON;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import org.json.JSONArray;
import org.json.JSONObject;

public class App {

    ArrayList<Modul> Curs = new ArrayList();

    private void crearCurs() {
        // Aquest mètode inicializa l'objecte "Curs" de la classe 
        // que no és més que un arrayList de mòduls

        // Definim els vectors per inicialitzar dades
        String[] moduls = {"Accés a Dades", "Programació de serveis i processos", "Desenvolupament d'interfícies", "Programació Multimèdia i dispositiud mòbils", "Sistemes de Gestió Empresarial", "Empresa i iniciativa emprenedora"};
        int[] hores = {6, 3, 6, 5, 5, 3};
        double[] notes = {8.45, 9.0, 8.0, 7.34, 8.2, 7.4};

        // Recorrem els vectors, creant els objectes
        // de tipus Modul i guardant-los en Curs
        for (int i = 0; i < moduls.length; i++) {
            Modul m = new Modul(moduls[i], hores[i], notes[i]);
            this.Curs.add(m);
        }
    }

    private JSONObject crearJSON() {

        // root element "Curs"
        JSONObject curs = new JSONObject();

        // JSONArray on emmagatzenarem cada element amb la info de cada modul (en forma de JSONObject)
        JSONArray jsarray = new JSONArray();

        // we populate the array with individual modules
        for (Modul m : this.Curs) {
            JSONObject modul_json = new JSONObject();

            modul_json.put("nom", m.getNom());
            modul_json.put("hores", m.getHores());
            modul_json.put("nota", m.getQualificacio());

            jsarray.put(modul_json);
        }

        // Create the curs element with the array
        curs.put("curs", jsarray);

        return (curs);
    }

    private void escriuJSON(String filename, JSONObject jso) {

        try {
            FileWriter file = new FileWriter(filename);
            file.write(jso.toString(4)); // 4 són els espais d'indentació
            file.close();

        } catch (IOException e) {
            System.out.println("Error, no es pot crear el fitxer " + filename);
        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.crearCurs();
        JSONObject cursJSON = app.crearJSON();
        app.escriuJSON("curs.json", cursJSON);
    }
}
